from __future__ import annotations

from typing import Any

from ca9.capabilities.models import CapabilityDiff

_KIND_LABELS = {
    "mcp_server": "MCP server",
    "mcp_tool": "MCP tool",
    "llm_provider": "LLM provider",
    "egress_sink": "Egress sink",
    "prompt": "Prompt",
    "agent_framework": "Agent framework",
    "cloud_storage": "Cloud storage",
    "agent_tool": "Agent tool",
}


def emit_markdown_diff(diff: CapabilityDiff, policy_result: dict[str, Any] | None = None) -> str:
    lines: list[str] = []

    lines.append("## ca9 -- Capability Diff (AI-BOM)")
    lines.append("")

    risk_level = diff.risk.level.upper()
    lines.append(f"**Risk:** {risk_level}")

    if policy_result:
        decision = policy_result.get("decision", "pass")
        if decision == "block":
            blocking = [
                r for r in policy_result.get("triggered_rules", []) if r["action"] == "block"
            ]
            if blocking:
                rule_ids = ", ".join(f"`{r['id']}`" for r in blocking)
                lines.append(f"**Decision:** Blocked by policy {rule_ids}")
        elif decision == "warn":
            lines.append("**Decision:** Warnings present")
        else:
            lines.append("**Decision:** Passed policy checks")
    lines.append("")

    if diff.assets_added or diff.assets_removed or diff.assets_changed:
        lines.append("### What changed (assets)")
        for asset in diff.assets_added:
            lines.append(f"- + {_KIND_LABELS.get(asset.kind, asset.kind)}: `{asset.id}`")
        for asset in diff.assets_changed:
            change = asset.change or "modified"
            lines.append(f"- ~ {_KIND_LABELS.get(asset.kind, asset.kind)} {change}: `{asset.id}`")
        for asset in diff.assets_removed:
            lines.append(f"- - {_KIND_LABELS.get(asset.kind, asset.kind)}: `{asset.id}`")
        lines.append("")

    if diff.capabilities_added or diff.capabilities_widened or diff.capabilities_removed:
        lines.append("### Capability delta (Power changes)")

        if diff.capabilities_added:
            lines.append("**Added**")
            for cap in diff.capabilities_added:
                evidence = ", ".join(cap.evidence[:3])
                lines.append(f"- `{cap.capability}` scope=`{cap.scope}`")
                lines.append(f"  Evidence: `{evidence}`")

        if diff.capabilities_widened:
            lines.append("**Widened**")
            for cap in diff.capabilities_widened:
                evidence = ", ".join(cap.evidence[:3])
                lines.append(f"- `{cap.capability}` from `{cap.from_scope}` -> `{cap.to_scope}`")
                lines.append(f"  Evidence: `{evidence}`")

        if diff.capabilities_removed:
            lines.append("**Removed**")
            for cap in diff.capabilities_removed:
                lines.append(f"- `{cap.capability}` scope=`{cap.scope}`")

        lines.append("")

    if diff.risk.reasons:
        lines.append("### Why this matters")
        for reason in diff.risk.reasons:
            lines.append(f"- {reason}")
        lines.append("")

    if policy_result and policy_result.get("decision") == "block":
        lines.append("### How to resolve")
        blocking = [r for r in policy_result.get("triggered_rules", []) if r["action"] == "block"]
        if blocking:
            lines.append("This PR is blocked by the following policy rules:")
            lines.append("")
            for rule in blocking:
                lines.append(f"**{rule['id']}**: {rule['message']}")
            lines.append("")
            lines.append("To resolve:")
            lines.append("- Review and address the policy violations")
            lines.append("- OR obtain security approval and add the `ca9-approved` label")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [ca9](https://github.com/duriantaco/ca9)*")

    return "\n".join(lines)
